site_name: Zeta2D
theme:
  name: material

  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  language: en

  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
      primary: indigo
      accent: cyan

    - scheme: slate
      toggle:
        icon: material/brightness-4 
        name: Switch to dark mode
      primary: teal
      accent: blue

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Salamence064/Zeta2D

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href = "https://github.com/Salamence064" target="_blank" rel="noopener">Thomas Ducote</a>
